### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Finlito** [YAL-GameMaker/window_shape#1]
im using the desktop friend demo but the transparency doesnt work, using 2022 lts

**Comment by YellowAfterlife** [comment]
Does the demo executable from itch work? And if so, does transparency work when you compile with YYC?

**Comment by Finlito** [comment]
Demo executable works, doesnt work with yyc when i build it however.

**Comment by YellowAfterlife** [comment]
And are there any errors in the Output? (or post your Output with compilation-runtime logs in general)

**Comment by Finlito** [comment]
well to even get the project running in the first place there were many issues with the dlls and autogen.gml, so i had to add the dlls from the itch demo and remove this part of the code 
![image](https://github.com/user-attachments/assets/ca897d88-3947-472c-af3d-0b95e11b0a89)

**Comment by Finlito** [comment]
this would be the error if i didnt 
![image](https://github.com/user-attachments/assets/9b75febd-b912-482a-99ae-39e687c1d154)

**Comment by YellowAfterlife** [comment]
You'll want to follow the [build guide](https://github.com/YAL-GameMaker/window_shape/blob/main/BUILD.md) instead of trying to blindly re-create configuration from the demo. The auto-generated files are auto-generated because that's a lot of legwork.

**Comment by Finlito** [comment]
I just found out (in a really stupid way) That i actually wasnt building with yyc, Sorry for wasting your time!
